# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=120)),
                ('ip', models.SlugField(max_length=30, unique=True)),
                ('name', models.TextField(max_length=120)),
            ],
        ),
    ]
