# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servermon', '0002_auto_20171114_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='channel_reply',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
