# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermon', '0003_server_channel_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='arch',
            field=models.CharField(default='testing', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='mac',
            field=models.CharField(default='testing', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='memory',
            field=models.CharField(default='testing', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='processor',
            field=models.CharField(default='testing', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=30),
        ),
    ]
