# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermon', '0004_auto_20171120_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='mac',
            field=models.CharField(max_length=30),
        ),
    ]
