# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servermon', '0005_auto_20171120_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ip',
            new_name='ipddress',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='os',
            new_name='system',
        ),
    ]
