# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servermon', '0006_auto_20171126_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ipddress',
            new_name='ipaddress',
        ),
    ]
